services:
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: learn
      POSTGRES_DB: learn
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    environment:
      - DATABASE_URL=postgres://learn:example@db:5432/learn
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - api
    working_dir: /app

volumes:
  pg_data:
  web_node_modules: