FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock* package-lock.json* ./
RUN npm install -g pnpm && \
    if [ -f yarn.lock ]; then yarn; \
    elif [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then pnpm i; \
    else npm install; fi

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]